#!/bin/bash
# Configuration ============================================
REPO_URL="https://raw.githubusercontent.com/mithubindia/vmenu/main"
BASE_DIR="/usr/local/share/vmenu"
CONFIG_FILE="$BASE_DIR/config.json"
CACHE_FILE="$BASE_DIR/cache.json"
UTILS_FILE="$BASE_DIR/utils.sh"
LOCAL_VERSION_FILE="$BASE_DIR/version.txt"
VENV_PATH="/opt/googletrans-env"

if [[ -f "$UTILS_FILE" ]]; then
    source "$UTILS_FILE"
fi


check_updates() {
    local INSTALL_SCRIPT="$BASE_DIR/install_proxmenux.sh"

    local REMOTE_VERSION
    REMOTE_VERSION=$(curl -fsSL "$REPO_URL/version.txt" | head -n 1)
    

    if [ -z "$REMOTE_VERSION" ]; then
        return 0
    fi
    

    local LOCAL_VERSION
    LOCAL_VERSION=$(head -n 1 "$LOCAL_VERSION_FILE")
    

    [ "$LOCAL_VERSION" = "$REMOTE_VERSION" ] && return 0
    

    if whiptail --title "$(translate "Update Available")" \
                --yesno "$(translate "New version available") ($REMOTE_VERSION)\n\n$(translate "Do you want to update now?")" \
                10 60 --defaultno; then
        msg_warn "$(translate "Starting ProxMenu update...")"

        if wget -qO "$INSTALL_SCRIPT" "$REPO_URL/install_proxmenux.sh"; then
            chmod +x "$INSTALL_SCRIPT"

            source "$INSTALL_SCRIPT"
        fi
    else
        msg_warn "$(translate "Update postponed. You can update later from the menu.")"
    fi
}



main_menu() {
    exec bash <(curl -fsSL "$REPO_URL/scripts/menus/main_menu.sh")
}


load_language
initialize_cache
check_updates
main_menu
